name: Docker Image CI

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [tools, nomad, tools-solo, tools-datawire]
        include:
          - image: tools
            directory: tools
            dockerfile: Dockerfile
          - image: nomad
            directory: nomad
            dockerfile: Dockerfile
          - image: tools-solo
            directory: tools
            dockerfile: Dockerfile-solo
          - image: tools-datawire
            directory: tools
            dockerfile: Dockerfile-datawire

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Check for changes
        id: check_for_changes
        run: |
          echo "::set-output name=change_count::$(git diff --name-only  HEAD^ HEAD | grep '${{ matrix.directory }}' | wc -l)"

      - name: Get dependencies
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          echo "changes: ${{ steps.check_for_changes.outputs.change_count }} event: ${{ github.event_name }}"

      - name: Build the Docker image
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          cd ${{ matrix.directory }}
          docker build . --file ${{ matrix.dockerfile }} --tag shipyardrun/${{ matrix.image }}:$(cat VERSION)

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push the Docker image
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          cd ${{ matrix.directory }}
          docker push shipyardrun/${{ matrix.image }}:$(cat VERSION)
          
      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: steps.check_for_changes.outputs.change_count != '0'
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
