name: Docker Image CI

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [tools, nomad, tools-solo, tools-datawire]
        include:
          - image: tools
            directory: tools
            dockerfile: Dockerfile
          - image: nomad
            directory: nomad
            dockerfile: Dockerfile
          - image: tools-solo
            directory: tools
            dockerfile: Dockerfile-solo
          - image: tools-datawire
            directory: tools
            dockerfile: Dockerfile-datawire

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Check for changes
        id: check_for_changes
        run: |
          echo "::set-output name=change_count::$(git diff --name-only  HEAD^ HEAD | grep '${{ matrix.directory }}' | wc -l)"

      - name: Get dependencies
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          echo "changes: ${{ steps.check_for_changes.outputs.change_count }} event: ${{ github.event_name }}"

      - name: Build the Docker image
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          cd ${{ matrix.directory }}
          docker build . --file ${{ matrix.dockerfile }} --tag gcr.io/shipyard-287511/${{ matrix.image }}:$(cat VERSION)

      - name: Setup GCP Tools
        if: steps.check_for_changes.outputs.change_count != '0'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCP_KEY }}

      - name: Docker Auth
        if: steps.check_for_changes.outputs.change_count != '0'
        run: gcloud auth configure-docker

      - name: Push the Docker image
        if: steps.check_for_changes.outputs.change_count != '0'
        run: |
          docker push gcr.io/shipyard-287511/${{ matrix.image }}:$(cat VERSION)
